export const raceCarCount = 7;
export const winnerCarCount = 10;
export const defaultServerAddress = `http://127.0.0.1:3000`;

export const selectParametrs = ['none', 'Sort winrate ASC', 'Sort winrate DESC', 'Sort time ASC', 'Sort time DESC', 'Sort by ID ASC', 'Sort by ID DESC'];
export const selectParametrsRequest = ['', '&_sort=wins&_order=ASC', '&_sort=wins&_order=DESC', '&_sort=time&_order=ASC', '&_sort=time&_order=DESC', '&_sort=id&_order=ASC', '&_sort=id&_order=DESC'];

export const carBrand: string[] = [
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'Cadillac',
  'Chevrolet',
  'Citroen',
  'Continental',
  'Daewoo',
  'Datsun',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'Haval',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'KIA',
  'Lada',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Maserati',
  'Mazda',
  'Mercedes-Benz',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Porsche',
  'Range Rover',
  'Ravon',
  'Renault',
  'Rolls-Royce',
  'Saab',
  'Skoda',
];

export const carModal: string[] = [
  'Challenger',
  'Charger',
  'Caravan',
  'X7',
  'X5',
  'X3',
  'X6 M',
  'X6',
  'X1',
  'X4',
  'C3',
  'C5',
  'Duster',
  'CR-V',
  'Corolla',
  'C4 Cactus',
  'DS3 Crossback',
  'C1',
  'C3',
  'Berlingo',
  'Crossback',
  'LC 500',
  'Rapid',
  'Largus',
  'Hatchback',
  'CX-5',
  'Sedan',
  'CX-30',
  'CX-9',
  'CX-3',
  'MX-5',
  'Phantom',
  'Camry',
  'Polo',
  'Cullinan',
  'Dawn',
  'Duster',
  'Sandero',
  'Logan',
  'Trafic',
  'Logan',
  'Captur',
  'RAV4',
  'Rio',
  'Solaris',
];

export const carColor: string[] = ['#eae5e6', '#785454', '#7a3fa2', '#636013', '#19d2cf', '#267e30', '#a44197', '#cabfbe', '#e80f0f', '#f0610e', '#f0ec0e', '#0ef02c', '#0ef0e1', '#0e74f1', '#5d0ef0', '#f00ebf'];
